# Generated by Django 3.0.4 on 2021-01-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_canpause',
            new_name='guest_can_pause',
        ),
    ]
